# Generated by Django 4.2.1 on 2023-05-28 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_predmeti_nositelj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='nositelj',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
