# Generated by Django 4.2.1 on 2023-05-29 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_predmeti_nositelj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Izgubio potpis', 'izgubio potpis'), ('Dobio potpis, nije polozio', 'dobio potpis, nije polozio'), ('Polozio predmet', 'polozio predmet')], default=26, max_length=50)),
                ('predmet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.predmeti')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
