# Generated by Django 4.2.1 on 2023-06-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_upisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upisi',
            old_name='predmet_id',
            new_name='predmet',
        ),
        migrations.RenameField(
            model_name='upisi',
            old_name='student_id',
            new_name='student',
        ),
    ]
